lantern/flask/flask_login_and_templates/practice/grocery_store/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from werkzeug.security import generate_password_hash, check_password_hash
from grocery_store.database import db
from grocery_store.models import User
from flask_login import login_user, login_required, logout_user

auth = Blueprint("auth", __name__)


@auth.route("/login")
def login():
    return render_template("login.html")


@auth.route("/login", methods=["POST"])
def login_post():
    email = request.form.get("email")
    password = request.form.get("password")
    remember = True if request.form.get("remember") else False

    user = User.query.filter_by(email=email).first()

    # check if user actually exists
    # take the user supplied password, hash it, and compare it to the hashed password in database
    if not user or not check_password_hash(user.password, password):
        flash("Please check your login details and try again.")
        return redirect(
            url_for("auth.login")
        )  # if user doesn't exist or password is wrong, reload the page
    login_user(user, remember=remember)
    # if the above check passes, then we know the user has the right credentials
    # login code goes here
    return redirect(url_for("main.profile"))


@auth.route("/signup")
def signup():
    return render_template("signup.html")


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))


@auth.route("/signup", methods=["POST"])
def signup_post():
    email = request.form.get("email")
    name = request.form.get("name")
    password = request.form.get("password")

    # if this returns a user, then the email already exists in database
    user = User.query.filter_by(email=email).first()

    # if a user is found, we want to redirect back to signup page so user can try again
    if user:
        flash("Email address already exists")
        return redirect(url_for("auth.signup"))

    # create new user with the form data. Hash the password so plaintext version isn't saved.
    new_user = User(
        email=email,
        name=name,
        password=generate_password_hash(password, method="sha256"),
    )

    # add the new user to the database
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for("auth.login"))

lantern/flask/flask_login_and_templates/practice/grocery_store/routes/main.py
from flask import Blueprint, render_template
from flask_login import current_user, login_required

from grocery_store.models import Good

main = Blueprint("main", __name__)


@main.route("/")
def index():
    return render_template("index.html")


@main.route("/profile")
@login_required
def profile():
    return render_template(
        "profile.html", user=current_user.name, email=current_user.email,
    )


@main.route("/user_orders_list")
@login_required
def orders():
    user_orders_list = []
    for order in current_user.orders:
        data = {
            "store": order.store.name,
            "date": order.created_time,
            "price": sum([good.good.price for good in order.order_lines]),
            "goods": {good.good.name: good.good.price for good in order.order_lines},
        }
        user_orders_list.append(data)
    return render_template("orders.html", orders=user_orders_list)


@main.route("/manage_stores")
@login_required
def stores():
    return render_template("stores.html", stores=current_user.manage_stores)


@main.route("/price-list")
def price_list():
    return render_template("price_list.html", goods=Good.query.all())

lantern/flask/flask_login_and_templates/practice/grocery_store/routes/stores.py
from flask import request
from flask_restful import Resource, marshal

from grocery_store.models import Store
from grocery_store.database import db
from grocery_store.routes.marshal_structure import stores_structure


class Stores(Resource):
    def get(self, store_id=None):
        if store_id:
            store = Store.query.get(store_id)
            if store:
                return marshal(store, stores_structure)
            return f"No such store with id: {store_id}"
        return marshal(Store.query.all(), stores_structure)

    def post(self):
        store = Store(**request.json)
        db.session.add(store)
        db.session.commit()
        return f"Successfully added a new store {store}"

    def put(self, store_id):
        store = Store.query.get(store_id)
        store.name = request.json.get("name", store.name)
        store.city = request.json.get("city", store.city)
        store.address = request.json.get("address", store.address)
        store.manager_id = request.json.get("manager_id", store.manager_id)
        db.session.commit()
        return f"Successfully updated Store with id: {store_id}"

    def delete(self, store_id):
        store = Store.query.get(store_id)
        db.session.delete(store)
        db.session.commit()
        return f"Successfully deleted Store with id: {store_id}"

lantern/flask/flask_login_and_templates/practice/grocery_store/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for("main.index") }}" class="navbar-item">
                                Home
                            </a>
                            <a href="{{ url_for("main.price_list") }}" class="navbar-item">
                                Price list
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for("main.profile") }}" class="navbar-item">
                                Profile
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for("main.orders") }}" class="navbar-item">
                                My Orders
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for("auth.login") }}" class="navbar-item">
                                Login
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for("auth.signup") }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for("auth.logout") }}" class="navbar-item">
                                Logout
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

lantern/flask/flask_login_and_templates/practice/grocery_store/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Flask Login Example
</h1>
<h2 class="subtitle">
  Easy authentication and authorization in Flask.
</h2>
{% endblock %}

lantern/flask/flask_login_and_templates/practice/grocery_store/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      <div class="notification is-danger">
        {{ messages[0] }}
      </div>
      {% endif %}
      {% endwith %}
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

lantern/flask/flask_login_and_templates/practice/grocery_store/templates/orders.html
{% extends "base.html" %}
{% block content %}
{% set sum = [0] -%}
    <h1 class="title">
        My Orders
    </h1>
    <table class="table" align="center">
        <thead>
        <tr>
            <th>Store</th>
            <th>Date</th>
            <th>Good</th>
            <th>Price</th>
        </tr>
        </thead>
        {%  for order in orders %}
                 <tr>
                    <td>{{ order["store"] }}</td>
                    <td>{{ order["date"] }}</td>
                    <td></td>
                    <td></td>
                </tr>
            {% for key, value in order["goods"].items() %}
                 <tr>
                    <td></td>
                    <td></td>
                    <td>{{ key }}</td>
                    <td>{{ value }}</td>
                </tr>
                {% if sum.append(sum.pop()+ value) -%}{% endif %}
            {% endfor %}
                  <tr>
                    <td></td>
                    <td></td>
                    <td><b>Order sum</b></td>
                    <td><b>{{ order["price"] }}</b></td>
                </tr>
        {% endfor %}
            <tr>
                <td></td>
                <td></td>
                <td><b>Total sum</b></td>
                <td><b>{{ sum[0] }}</b></td>
            </tr>
        </table>
{% endblock %}

lantern/flask/flask_login_and_templates/practice/grocery_store/templates/price_list.html
{% extends "base.html" %}

{% block content %}
    <h1 class="title">
        Price list
    </h1>
    <table class="table" align="center">
        <thead>
        <tr>
            <th>brand</th>
            <th>name</th>
            <th>price</th>
        </tr>
        </thead>
        <tbody>
        {% for good in goods %}
            <tr>
                <td>{{ good["brand"] }}</td>
                <td>{{ good["name"] }}</td>
                <td>{{ good["price"] }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

lantern/flask/flask_login_and_templates/practice/grocery_store/templates/profile.html
{% extends "base.html" %}

{% block content %}
    <h1 class="title">
        Welcome, {{ user }}!
    </h1>
    <h2>Your email is "{{ email }}"</h2>
    <hr>
    <h3><a href="{{ url_for("main.orders") }}">Click HERE to see your orders</a></h3>
    {% if current_user.manage_stores %}
        <hr>
        <h2><a href="{{ url_for("main.stores") }}">Click HERE to see your managed stores</a></h2>
    {% endif %}
{% endblock %}

lantern/flask/flask_login_and_templates/practice/grocery_store/templates/signup.html
{% extends "base.html" %}


{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
      <!-- Flashed messages area -->
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      <div class="notification is-danger">
        {{ messages[0] }}. Go to <a href="{{ url_for("auth.login") }}">login page</a>.
      </div>
      {% endif %}
      {% endwith %}
      <!-- End of flashed messages area -->
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}

lantern/flask/flask_login_and_templates/practice/grocery_store/templates/stores.html
{% extends "base.html" %}

{% block content %}
    <h2 class="title">
        My Stores
    </h2>
    <table style="width:100%" class="table">
        <tr>
            <th>Name</th>
            <th>City</th>
            <th>Address</th>
        </tr>
        {% for store in stores %}
            <tr>
                <td>{{ store.name }}</td>
                <td>{{ store.city }}</td>
                <td>{{ store.address }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}